### PR TITLE
S82 mobile

### PR DESCRIPTION
**Pull request by stuttskl**
- refactored/revamped desktop version of page using bootstrap containers (so that we can use their responsive breakpoints for mobile)
- mobile layout/most of the css is completed

### CODE REVIEW

**Comment by sjpaige** [comment]
After inspecting the code and running it on my machine (with both desktop and mobile user agent), I noticed that the new mobile nav menu doesn't close when clicking it again, it will stay open if you don't choose an option. Is this behavior intended?

The visuals are matching up very closely to the concepts in both the mobile and desktop designs.

I think we can merge these changes depending on how we feel about the menu.

**Comment by stuttskl** [comment]
@sjpaige , no, that is not the intended behavior. I made a slight change such that the mobile nav menu will open/close when the hamburger menu is clicked, but do you think we should add functionality such that the mobile nav will close when the user clicks outside of it (i.e. further down on the page)?

**Comment by sjpaige** [comment]
> @sjpaige , no, that is not the intended behavior. I made a slight change such that the mobile nav menu will open/close when the hamburger menu is clicked, but do you think we should add functionality such that the mobile nav will close when the user clicks outside of it (i.e. further down on the page)?

@stuttskl Glad we can get that updated. Yes, I think it should be able to close when clicks outside.

**Comment by sjpaige** [comment]
> > @sjpaige , no, that is not the intended behavior. I made a slight change such that the mobile nav menu will open/close when the hamburger menu is clicked, but do you think we should add functionality such that the mobile nav will close when the user clicks outside of it (i.e. further down on the page)?
> 
> @stuttskl Glad we can get that updated. Yes, I think it should be able to close when clicks outside.

Amended. Per slack discussion we're going to finalize this for now.

**Pull request merged**
